//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pens()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_Pen { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string PricePen { get; set; }
        public int id_TypePen { get; set; }
        public int id_Company { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual TypePen TypePen { get; set; }
        public int CompareTo(object other)
        {
            var obj = other as Pens;
            return Name.CompareTo(obj.Name);
        }
        public int CompareTo(object other, int a)
        {
            var obj = other as Pens;
            return id_TypePen.CompareTo(obj.id_TypePen);
        }
        public int CompareTo(object other, int b, int c)
        {
            var obj = other as Pens;
            return Color.CompareTo(obj.Color);
        }
    }
}
